# =============================================================================
# Metricbeat — Stack Monitoring + xost/konteyner metrikalari
# =============================================================================

metricbeat.modules:
  # xpack.enabled: true  →  Kibana'da "Stack Monitoring" sahifasi ishlaydi
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ["${ELASTIC_HOSTS}"]
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}

  - module: kibana
    xpack.enabled: true
    period: 10s
    hosts: ["${KIBANA_HOSTS}"]
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}

  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

  # /hostfs orqali xostning o'zini ko'radi
  - module: system
    metricsets: ["cpu", "load", "memory", "network", "process_summary"]
    period: 30s
  - module: system
    metricsets: ["filesystem", "fsstat"]
    period: 5m
    processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

setup.ilm.enabled: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOSTS}"]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

logging.level: info
logging.metrics.enabled: false